import React from 'react';
import { ArrowLeft } from 'lucide-react';

export const PrivacyPolicySection: React.FC = () => {
  return (
    <section className="py-24 px-4 sm:px-6 lg:px-8 bg-[#F1E2E2] text-[#1a232b] relative min-h-screen">
      <div className="max-w-4xl mx-auto pt-10">
        
        {/* Back Button */}
        <div className="mb-8 relative z-10">
          <a
            href="/"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl neu-raised-light hover:neu-raised-light-hover text-sm font-bold uppercase tracking-wider text-[#3291B6] transition-all cursor-pointer"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Home</span>
          </a>
        </div>

        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full neu-inset-light text-xs font-mono font-bold tracking-wider text-[#3291B6] mb-4">
            <span>LEGAL DOCUMENTATION</span>
          </div>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-[#101820] font-sans">
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm font-mono text-gray-500">
            Last updated: July 28, 2026
          </p>
        </div>

        {/* Content Container */}
        <div className="p-8 sm:p-12 rounded-3xl neu-raised-light bg-[#F1E2E2] border border-white/80 shadow-2xl relative prose prose-slate max-w-none text-sm text-gray-700 leading-relaxed font-sans">
          
          <p className="mb-6">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p className="mb-8">
            We use Your Personal Data to provide and improve the Service. We collect, use, and disclose Your information as described in this Privacy Policy and, where required by applicable law, only where We have a valid legal basis to do so, including Your consent (where consent is required).
          </p>

          <h2 className="text-xl font-bold text-[#101820] mt-10 mb-4 border-b border-gray-300 pb-2">Interpretation and Definitions</h2>
          
          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Interpretation</h3>
          <p className="mb-6">
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Definitions</h3>
          <p className="mb-4">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-6 space-y-3 mb-8">
            <li><strong>Account</strong> means a unique account created for You to access Our Service or parts of Our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Parallax Nest, 206 N Spring St, Los Angeles, CA.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website, among its many uses.</li>
            <li><strong>Country/State</strong> refers to: California, United States.</li>
            <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>User</strong> means any individual who accesses or uses the Service.</li>
            <li><strong>Website</strong> refers to parallaxnest.com, accessible from https://parallaxnest.com/.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="text-xl font-bold text-[#101820] mt-10 mb-4 border-b border-gray-300 pb-2">Collecting and Using Your Personal Information</h2>
          
          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Types of Data Collected</h3>
          <h4 className="font-bold mt-4 mb-2">Personal Data</h4>
          <p className="mb-4">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc pl-6 space-y-2 mb-6">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
          </ul>

          <h4 className="font-bold mt-4 mb-2">Usage Data</h4>
          <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
          <p className="mb-4">
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of Our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p className="mb-4">
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>
          <p className="mb-8">
            We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Tracking Technologies and Cookies</h3>
          <p className="mb-4">
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
          </p>
          <ul className="list-disc pl-6 space-y-3 mb-6">
            <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of Our Service.</li>
            <li><strong>Web Beacons.</strong> Certain sections of Our Service and Our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
          </ul>
          <p className="mb-4">
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
          </p>
          <p className="mb-4">
            Where required by law, We use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.
          </p>
          <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
          <div className="bg-[#e8d6d6] p-4 rounded-xl neu-inset-light mb-6 space-y-4">
            <div>
              <strong className="block text-[#101820]">Necessary / Essential Cookies</strong>
              <span className="text-xs font-mono text-[#3291B6] block mb-1">Type: Session Cookies | Administered by: Us</span>
              <p className="text-sm">These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</p>
            </div>
            <div>
              <strong className="block text-[#101820]">Cookies Policy / Notice Acceptance Cookies</strong>
              <span className="text-xs font-mono text-[#3291B6] block mb-1">Type: Persistent Cookies | Administered by: Us</span>
              <p className="text-sm">These Cookies identify whether users have accepted the use of cookies on the Website.</p>
            </div>
            <div>
              <strong className="block text-[#101820]">Functionality Cookies</strong>
              <span className="text-xs font-mono text-[#3291B6] block mb-1">Type: Persistent Cookies | Administered by: Us</span>
              <p className="text-sm">These Cookies allow Us to remember choices You make when You use the Website, such as remembering Your Account login details or language preference.</p>
            </div>
          </div>
          <p className="mb-8">
            For more information about the cookies We use and Your choices regarding cookies, please visit Our Cookies Policy or the Cookies section of Our Privacy Policy.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Use of Your Personal Data</h3>
          <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc pl-6 space-y-3 mb-8">
            <li><strong>To provide and maintain Our Service</strong>, including to monitor the usage of Our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li><strong>To provide You with news, special offers, and general information</strong> about other goods, services and events which We offer that are similar to those that You have already purchased or inquired about.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of Our promotional campaigns, and evaluating and improving Our Service, products, services, marketing and Your experience.</li>
          </ul>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Sharing of Your Personal Data</h3>
          <p className="mb-4">We may share Your Personal Data in the following situations:</p>
          <ul className="list-disc pl-6 space-y-3 mb-8">
            <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of Our Service, and to contact You.</li>
            <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
            <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case We will require those affiliates to honor this Privacy Policy.</li>
            <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
            <li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside the Service.</li>
            <li><strong>With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
          </ul>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Retention of Your Personal Data</h3>
          <p className="mb-4">
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with Our legal obligations, resolve disputes, and enforce Our legal agreements and policies.
          </p>
          <p className="mb-4">We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
          <ul className="list-disc pl-6 space-y-3 mb-6">
            <li><strong>User Accounts:</strong> retained for the duration of Your Account relationship plus up to 24 months after account closure.</li>
            <li><strong>Support tickets and correspondence:</strong> up to 24 months from the date of ticket closure.</li>
            <li><strong>Chat transcripts:</strong> up to 24 months for quality assurance and staff training purposes.</li>
            <li><strong>Website analytics data:</strong> up to 24 months from the date of collection.</li>
            <li><strong>Server logs:</strong> up to 24 months for security monitoring and troubleshooting purposes.</li>
          </ul>
          <p className="mb-8">
            When retention periods expire, We securely delete or anonymize Personal Data according to Our procedures (Deletion, Backup retention, Anonymization).
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Transfer of Your Personal Data</h3>
          <p className="mb-8">
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. This means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of Your jurisdiction.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Delete Your Personal Data</h3>
          <p className="mb-8">
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account, if You have one, or contacting Us.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Disclosure of Your Personal Data</h3>
          <ul className="list-disc pl-6 space-y-3 mb-8">
            <li><strong>Business Transactions:</strong> If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</li>
            <li><strong>Law Enforcement:</strong> Under certain circumstances, the Company may disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</li>
            <li><strong>Other Legal Requirements:</strong> The Company may disclose Your Personal Data in the good-faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate possible wrongdoing in connection with the Service, protect the personal safety of Users of the Service or the public, or protect against legal liability.</li>
          </ul>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Security of Your Personal Data</h3>
          <p className="mb-8">
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Children's and Minors' Privacy</h3>
          <p className="mb-8">
            The Service is not directed to, and We do not knowingly collect Personal Information from, anyone under the age of 16. If You are a parent or guardian and You believe Your child has provided Us with Personal Information, please contact Us.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Links to Other Websites</h3>
          <p className="mb-8">
            Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Changes to this Privacy Policy</h3>
          <p className="mb-8">
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and update the "Last updated" date at the top of this Privacy Policy.
          </p>

          <h3 className="text-lg font-bold text-[#3291B6] mt-6 mb-3">Contact Us</h3>
          <p className="mb-8">
            If You have any questions about this Privacy Policy, You can contact Us:
            <br />
            <strong>By email:</strong> <a href="mailto:connect@parallaxnest.com" className="text-[#3291B6] hover:underline">connect@parallaxnest.com</a>
          </p>

        </div>
      </div>
    </section>
  );
};
